version: '2'
services:
    pratiche01-app:
        image: pratiche01
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://pratiche01-mysql:3306/pratiche01?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    pratiche01-mysql:
        extends:
            file: mysql.yml
            service: pratiche01-mysql
